# -*- coding: utf-8 -*-
"""Data Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19S8jqoWExJrSSykWaS1c-ytcnn_2dAnW
"""

!pip install google-play-scraper

from google_play_scraper import app

import pandas as pd

import numpy as np

# doordash com.dd.doordash
# ubereats com.ubercab.eats
# Grubhub com.grubhub.android
# Instacart com.instacart.clien
from google_play_scraper import Sort, reviews


result, continuation_token = reviews(
    app_id='com.instacart.clien',
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    count=10000, # defaults to 100
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT
)

df = pd.DataFrame(result)
df

df.to_csv('Instacart_Nov10_10000.csv', index=False)
from google.colab import drive
drive.mount('/content/drive')
!cp -r "/content/Instacart_Nov10_10000.csv" "/content/drive/My Drive/DS-GA1007-Project/Instacart_Nov10_10000.csv"